language: node_js
script: "./travis.sh"
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_a936f2530bd1_key -iv $encrypted_a936f2530bd1_iv
  -in service_account.json.enc -out service_account.json -d
